In [1]:
import pandas
import numpy as np
import rdkit

In [3]:
data_path="/home/pangkuan/dev/SDL-LNP/model/4CR-1920.csv"
df = pandas.read_csv(data_path)
df

,RLU (log2),mol,Markush code
0,5.612732,CCCCCCCCCCCCCCCCCC(=O)N(CCCCCCCCC)C(CCN(C)C)C(...,"(R3(1):01, R2(4):01, R1(6):01, R4(9):01)"
1,1.038637,CCCCCCCCCCCCCCCCCC(=O)N(CCCCCCCCC)C(CCN(C)C)C(...,"(R3(1):01, R2(4):01, R1(6):01, R4(9):02)"
2,1.899728,CCCCCCCCCCCCCCCCCC(=O)N(CCCCCCCCC)C(CCN(C)C)C(...,"(R3(1):01, R2(4):01, R1(6):01, R4(9):03)"
3,2.307012,CCCCCCCCCCCCCCCCCC(=O)N(CCCCCCCCC)C(CCN(C)C)C(...,"(R3(1):01, R2(4):01, R1(6):01, R4(9):04)"
4,1.088917,CCCCCCCCCCCCCCCCCC(=O)N(CCCCCCCCC)C(CCN(C)C)C(...,"(R3(1):01, R2(4):01, R1(6):01, R4(9):05)"
...,...,...,...
1915,1.231326,CCCCCCCCC(CCCCCC)C(=O)OCCCCCN(C(C1CCNCC1)C(=O)...,"(R3(1):04, R2(4):04, R1(6):20, R4(9):02)"
1916,3.380320,CCCCCCCCC(CCCCCC)C(=O)OCCCCCN(C(C1CCNCC1)C(=O)...,"(R3(1):04, R2(4):04, R1(6):20, R4(9):03)"
1917,9.850832,CCCCCCCCC(CCCCCC)C(=O)OCCCCCN(C(C1CCNCC1)C(=O)...,"(R3(1):04, R2(4):04, R1(6):20, R4(9):04)"
1918,9.236222,CCCCCCCCC(CCCCCC)C(=O)OCCCCCN(C(C1CCNCC1)C(=O)...,"(R3(1):04, R2(4):04, R1(6):20, R4(9):05)"
1919,2.927649,CCCCCCCCC(CCCCCC)C(=O)OCCCCCN(C(C1CCNCC1)C(=O)...,"(R3(1):04, R2(4):04, R1(6):20, R4(9):06)"

In [5]:
# create a smiles.csv file containing at every line smile_str, num_conformers, smile_str. (two smile_str)
num_conformers = 10
file = open("smiles.csv", "w")
file.write("smiles,num_conformers,smiles\n")
for index, row in df.iterrows():
    smiles = row['mol']
    num_conformers = num_conformers
    file.write(smiles + "," + str(num_conformers) + "," + smiles + "\n")
file.close()