In [1]:
from rdkit import Chem
from mordred import Calculator, descriptors
import pandas as pd

In [2]:
# Define a SMILES string
smiles = 'CCO'  # Example: Ethanol

# Convert SMILES to RDKit molecule object
mol = Chem.MolFromSmiles(smiles)

# Initialize Mordred calculator with all descriptors
calc = Calculator(descriptors, ignore_3D=True)

# Calculate descriptors
result = calc(mol)

# Convert the result to a dictionary or a pandas DataFrame for better usability
desc_dict = result.asdict()

desc_df = pd.DataFrame([desc_dict])

# Display the DataFrame
desc_df

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,1.414214,1.414214,0,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,46.041865,5.115763,4,0,6.0,4.0,2.25,1.0

In [3]:
def get_mordred_descriptors(smiles_lst):
    mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_lst]
    calc = Calculator(descriptors)
    result = calc.pandas(mols)
    return result

In [4]:
get_mordred_descriptors(['CCO', 'CCN'])

100%|██████████| 2/2 [00:00<00:00, 18.48it/s]

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,1.414214,1.414214,0,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,46.041865,5.115763,4,0,6.0,4.0,2.25,1.0
1,1.414214,1.414214,0,1,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,45.057849,4.505785,4,0,6.0,4.0,2.25,1.0